version: '2'

services:
  prestashop:
    build: ./docker/prestashop
    ports:
      - 80:80
    links:
      - mariadb:mariadb
      - rediscache:rediscache
    depends_on:
      - mariadb
    volumes:
      - ./docker/common:/scripts
      - ./formitheme:/var/www/html/themes/formitheme
      - ./public_html:/var/www/html
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=0
      - DB_PREFIX=ps_

#  rediscache:
#    build: ./docker/redis
#    ports:
#      - 6379:6379

  mariadb:
    build: ./docker/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    ports:
      - 81:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root